# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Party.create(:name => "Sloboda a Solidarita", :acronym => "SaS", :logo_path => "/images/parties/sas.jpg" )
Party.create(:name => "Strana maďarskej koalície", :acronym => "SMK", :logo_path => "/images/parties/smk.jpg")
Party.create(:name => "Misia 21", :acronym => "Misia 21", :logo_path => "/images/parties/misia21.jpg")
Party.create(:name => "Slobodné Fórum", :acronym => "SF", :logo_path => "/images/parties/sf.jpg")
Party.create(:name => "Ľudová strana - Hnutie za demokratické Slovensko ", :acronym => "ĽS-HZDS", :logo_path => "/images/parties/hzds.jpg")
Party.create(:name => "Hnutie za demokraciu", :acronym => "HZD", :logo_path => "/images/parties/hzd.jpg")
Party.create(:name => "Strana zelených", :acronym => "SZ", :logo_path => "/images/parties/sz.jpg")
Party.create(:name => "Občianski liberáli", :acronym => "OL", :logo_path => "/images/parties/ol.jpg")
Party.create(:name => "Slovenská národná koalícia - Slovenská vzájomnosť", :acronym => "SLNKO", :logo_path => "")
Party.create(:name => "Kresťanskodemokratické hnutie", :acronym => "KDH", :logo_path => "/images/parties/kdh.jpg")
Party.create(:name => "Slovenská národná strana", :acronym => "SNS", :logo_path => "/images/parties/sns.jpg")
Party.create(:name => "Európska demokratická strana", :acronym => "EDS", :logo_path => "/images/parties/eds.jpg")
Party.create(:name => "Slovenská ľudová strana", :acronym => "SĽS", :logo_path => "/images/parties/.jpg")
Party.create(:name => "Strana demokratickej ľavice", :acronym => "SDĽ", :logo_path => "/images/parties/sdl.jpg")
Party.create(:name => "Agrárna strana vidieka", :acronym => "ASV", :logo_path => "/images/parties/asv.jpg")
Party.create(:name => "Aliancia nového občana", :acronym => "ANO", :logo_path => "/images/parties/ano.jpg")
Party.create(:name => "Nová demokracia", :acronym => "ND", :logo_path => "/images/parties/nd.jpg")
Party.create(:name => "Strana práce", :acronym => "SP", :logo_path => "/images/parties/.jpg")
Party.create(:name => "Strana zelených Slovenska", :acronym => "SZS", :logo_path => "")
Party.create(:name => "Slovenská demokratická a kresťanská únia - Demokratická strana", :acronym => "SDKÚ-DS", :logo_path => "/images/parties/sdku.jpg")
Party.create(:name => "Zelená vlna", :acronym => "ZV", :logo_path => "/images/parties/zv.png")
Party.create(:name => "Občianska konzervatívna strana", :acronym => "OKS", :logo_path => "/images/parties/oks.jpg")
Party.create(:name => "Konzervatívni demokrati Slovenska", :acronym => "KDS", :logo_path => "/images/parties/kds.jpg")
Party.create(:name => "Prosperita Slovenska", :acronym => "PS", :logo_path => "")
Party.create(:name => "Liberálna strana", :acronym => "LS", :logo_path => "")
Party.create(:name => "Komunistická strana Slovenska", :acronym => "KSS", :logo_path => "/images/parties/kss.jpg")
Party.create(:name => "Občianski kandidáti", :acronym => "OK", :logo_path => "/images/parties/ok.jpg")
Party.create(:name => "SMER - sociálna demokracia", :acronym => "SMER-SD", :logo_path => "/images/parties/smer.jpg")
Party.create(:name => "MOST-HÍD", :acronym => "MOST-HÍD", :logo_path => "/images/parties/most-hid.jpg")
Party.create(:name => "Demokratická strana", :acronym => "DS", :logo_path => "/images/parties/ds.jpg")
Party.create(:name => "Ľavicový blok", :acronym => "ĽB", :logo_path => "/images/parties/lb.jpg")
