# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Party.create(:name => "SaS")
Party.create(:name => "SMK")
Party.create(:name => "Misia 21")
Party.create(:name => "SF")
Party.create(:name => "HZDS")
Party.create(:name => "HZD")
Party.create(:name => "SZ")
Party.create(:name => "OL")
Party.create(:name => "SNK")
Party.create(:name => "KDH")
Party.create(:name => "SNS")
Party.create(:name => "EDS")
Party.create(:name => "SĽS")
Party.create(:name => "SDĽ")
Party.create(:name => "ASV")
Party.create(:name => "ANO")
Party.create(:name => "ND")
Party.create(:name => "SP")
Party.create(:name => "SZS")
Party.create(:name => "ĽS-HZDS")
Party.create(:name => "SDKÚ")
Party.create(:name => "ZV")
Party.create(:name => "OKS")
Party.create(:name => "KDS")
Party.create(:name => "PS")
Party.create(:name => "LS")
Party.create(:name => "KSS")
Party.create(:name => "ZS")
Party.create(:name => "OK")
Party.create(:name => "SMER")
Party.create(:name => "MOST-HÍD")
Party.create(:name => "Nádej")
Party.create(:name => "DS")
Party.create(:name => "ĽB")
