# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Party.create(:acronym => "SaS")
Party.create(:acronym => "SMK")
Party.create(:acronym => "Misia 21")
Party.create(:acronym => "SF")
Party.create(:acronym => "HZDS")
Party.create(:acronym => "HZD")
Party.create(:acronym => "SZ")
Party.create(:acronym => "OL")
Party.create(:acronym => "SNK")
Party.create(:acronym => "KDH")
Party.create(:acronym => "SNS")
Party.create(:acronym => "EDS")
Party.create(:acronym => "SĽS")
Party.create(:acronym => "SDĽ")
Party.create(:acronym => "ASV")
Party.create(:acronym => "ANO")
Party.create(:acronym => "ND")
Party.create(:acronym => "SP")
Party.create(:acronym => "SZS")
Party.create(:acronym => "ĽS-HZDS")
Party.create(:acronym => "SDKÚ")
Party.create(:acronym => "ZV")
Party.create(:acronym => "OKS")
Party.create(:acronym => "KDS")
Party.create(:acronym => "PS")
Party.create(:acronym => "LS")
Party.create(:acronym => "KSS")
Party.create(:acronym => "ZS")
Party.create(:acronym => "OK")
Party.create(:acronym => "SMER")
Party.create(:acronym => "MOST-HÍD")
Party.create(:acronym => "Nádej")
Party.create(:acronym => "DS")
Party.create(:acronym => "ĽB")
